package com.rath0darya.deleteme;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;

public class MainActivity extends Activity{
  LinearLayout content;TextView title,subtitle;EditText input;Button action;TextView navScan,navResults,navSettings;ArrayList<View> resultViews=new ArrayList<>();
  final int ink=Color.rgb(22,22,24),muted=Color.rgb(105,105,112),surface=Color.rgb(247,247,249),line=Color.rgb(225,225,230),green=Color.rgb(25,125,70),red=Color.rgb(190,45,45),amber=Color.rgb(185,110,20); final ExecutorService ex=Executors.newSingleThreadExecutor();
  static final String X="https://api.xposedornot.com/v1/check-email/";static final String B="https://raw.githubusercontent.com/Persprotect/data-broker-opt-out-list/main/data-brokers.json";
  public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.WHITE);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);build();}
  TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;} LinearLayout.LayoutParams lp(int w,int h){return new LinearLayout.LayoutParams(w,h);} GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
  LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(18,17,18,17);c.setBackground(bg(surface,18));LinearLayout.LayoutParams p=lp(-1,-2);p.bottomMargin=10;c.setLayoutParams(p);return c;}
  void build(){
    LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.WHITE);
    LinearLayout appbar=new LinearLayout(this);appbar.setGravity(Gravity.CENTER_VERTICAL);appbar.setPadding(20,8,20,8);TextView logo=tv("delete",24,ink);logo.setTypeface(Typeface.DEFAULT,Typeface.BOLD);appbar.addView(logo,lp(0,58));((LinearLayout.LayoutParams)logo.getLayoutParams()).weight=1;TextView shield=tv("● Private",12,green);appbar.addView(shield);root.addView(appbar);
    content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(20,8,20,18);ScrollView sv=new ScrollView(this);sv.addView(content);root.addView(sv,lp(-1,0));((LinearLayout.LayoutParams)sv.getLayoutParams()).weight=1;
    LinearLayout bottom=new LinearLayout(this);bottom.setGravity(Gravity.CENTER);bottom.setPadding(8,7,8,8);bottom.setBackgroundColor(Color.WHITE);String[] ns={"⌕\nScan","▣\nResults","⚙\nSettings"};TextView[] vv=new TextView[3];for(int i=0;i<3;i++){vv[i]=tv(ns[i],12,muted);vv[i].setGravity(Gravity.CENTER);bottom.addView(vv[i],lp(0,58));((LinearLayout.LayoutParams)vv[i].getLayoutParams()).weight=1;}navScan=vv[0];navResults=vv[1];navSettings=vv[2];navScan.setTextColor(ink);navScan.setTypeface(Typeface.DEFAULT,Typeface.BOLD);navResults.setOnClickListener(v->showResults());navScan.setOnClickListener(v->showScan());navSettings.setOnClickListener(v->showSettings());root.addView(bottom);setContentView(root);showScan();
  }
  void header(String h,String s){content.removeAllViews();title=tv(h,30,ink);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);title.setPadding(0,20,0,5);content.addView(title);subtitle=tv(s,15,muted);subtitle.setLineSpacing(2,1);subtitle.setPadding(0,0,0,20);content.addView(subtitle);}
  void showScan(){navScan.setTextColor(ink);navResults.setTextColor(muted);navSettings.setTextColor(muted);header("Find your data","Check your email for known breaches and see official privacy removal options.");LinearLayout c=card();TextView l=tv("WHAT DO YOU WANT TO CHECK?",12,muted);l.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(l);input=new EditText(this);input.setSingleLine(true);input.setTextSize(16);input.setHint("Enter your email");input.setPadding(16,0,16,0);GradientDrawable f=bg(Color.WHITE,15);f.setStroke(2,line);input.setBackground(f);LinearLayout.LayoutParams ip=lp(-1,58);ip.topMargin=9;c.addView(input,ip);content.addView(c);action=new Button(this);action.setText("Find my data");action.setAllCaps(false);action.setTextSize(16);action.setTextColor(Color.WHITE);action.setTypeface(Typeface.DEFAULT,Typeface.BOLD);action.setBackground(bg(ink,16));action.setOnClickListener(v->scan());LinearLayout.LayoutParams ap=lp(-1,56);ap.topMargin=4;content.addView(action,ap);LinearLayout info=card();info.setBackground(bg(Color.rgb(250,250,252),16));info.addView(tv("How it works",15,ink));info.addView(tv("1. We check public breach data.\n2. We show confirmed matches separately.\n3. You decide which removal option to use.",13,muted));content.addView(info);}
  void scan(){String e=input.getText().toString().trim();if(!android.util.Patterns.EMAIL_ADDRESS.matcher(e).matches()){input.setError("Enter a valid email address");return;}action.setEnabled(false);action.setText("Searching…");ex.execute(()->{try{ArrayList<String> m=new ArrayList<>();String s=get(X+URLEncoder.encode(e,"UTF-8")+"?details=true");JSONObject o=new JSONObject(s);JSONArray a=o.optJSONArray("breaches");if(a==null)a=o.optJSONArray("data");if(a!=null)for(int i=0;i<a.length();i++){Object q=a.get(i);String n=q instanceof JSONObject?((JSONObject)q).optString("name",((JSONObject)q).optString("title","Breach")):String.valueOf(q);if(!n.isEmpty()&&!m.contains(n))m.add(n);}runOnUiThread(()->{showResultPage(m);});}catch(Exception z){runOnUiThread(()->{action.setEnabled(true);action.setText("Try again");Toast.makeText(this,"Search failed. Check your connection.",Toast.LENGTH_LONG).show();});}});}
  void showResultPage(ArrayList<String> m){navScan.setTextColor(muted);navResults.setTextColor(ink);navSettings.setTextColor(muted);header("Your results",m.size()+" confirmed breach match"+(m.size()==1?"":"es")+" found");if(m.isEmpty()){LinearLayout c=card();TextView x=tv("✓",34,green);x.setGravity(Gravity.CENTER);c.addView(x);TextView h=tv("No confirmed matches",19,ink);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setGravity(Gravity.CENTER);c.addView(h);TextView d=tv("No match was returned by the checked breach source.",13,muted);d.setGravity(Gravity.CENTER);c.addView(d);content.addView(c);}else for(String n:m){LinearLayout c=card();TextView tag=tv("CONFIRMED MATCH",11,Color.WHITE);tag.setTypeface(Typeface.DEFAULT,Typeface.BOLD);tag.setGravity(Gravity.CENTER);tag.setPadding(10,5,10,5);tag.setBackground(bg(red,30));c.addView(tag,lp(-2,30));TextView h=tv(n,17,ink);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);LinearLayout.LayoutParams hp=lp(-1,-2);hp.topMargin=9;c.addView(h,hp);c.addView(tv("Your email was reported in this breach.",13,muted));content.addView(c);}LinearLayout c=card();c.addView(tv("Removal options",19,ink));c.addView(tv("The app can show official opt-out routes. These are not proof that a broker has your data.",13,muted));Button b=button("View removal directory");b.setOnClickListener(v->showDirectory());c.addView(b);content.addView(c);}
  void showResults(){showResultPage(new ArrayList<String>());}
  void showDirectory(){header("Removal directory","Official opt-out routes. Choose a service only when you want to request removal.");new Thread(()->{try{Object r=new JSONTokener(get(B)).nextValue();JSONArray a=r instanceof JSONArray?(JSONArray)r:((JSONObject)r).optJSONArray("data");if(a==null&&r instanceof JSONObject)a=((JSONObject)r).optJSONArray("brokers");final JSONArray aa=a;runOnUiThread(()->{if(aa==null)return;for(int i=0;i<aa.length();i++){JSONObject o=aa.optJSONObject(i);if(o==null)continue;String n=first(o,"company","name","broker"),u=first(o,"optOutUrl","opt_out_url","optout_url","opt_out","url");if(n.isEmpty()||u.isEmpty())continue;LinearLayout c=card();c.addView(tv(n,16,ink));Button x=button("Open official removal option");x.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception ignored){}});c.addView(x);content.addView(c);}});}catch(Exception ignored){}}).start();}
  void showSettings(){navScan.setTextColor(muted);navResults.setTextColor(muted);navSettings.setTextColor(ink);header("Settings","Simple controls for a privacy-first app.");LinearLayout c=card();c.addView(tv("Privacy",18,ink));c.addView(tv("DeleteMe does not require an account. Scan results are kept only in app memory in this version.",14,muted));content.addView(c);}
  Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setTextColor(ink);b.setBackground(bg(Color.WHITE,13));LinearLayout.LayoutParams p=lp(-1,48);p.topMargin=10;b.setLayoutParams(p);return b;}
  static String first(JSONObject o,String...k){for(String x:k){String v=o.optString(x,"");if(!v.trim().isEmpty())return v.trim();}return "";}static String get(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(20000);c.setRequestProperty("Accept","application/json");int z=c.getResponseCode();if(z<200||z>=300)throw new IOException("HTTP "+z);InputStream i=c.getInputStream();ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=i.read(b))>0)o.write(b,0,n);i.close();return o.toString(StandardCharsets.UTF_8.name());}
  protected void onDestroy(){ex.shutdownNow();super.onDestroy();}
}
