const API='/api';const $=id=>document.getElementById(id);let found=[];let scanning=false;
function profile(){const identifier=$('identifier').value.trim(),v=id=>$(id).value.trim();const p={identifier,first_name:v('firstName'),last_name:v('lastName'),email:'',phone:'',address:v('address'),city:v('city'),state:v('state'),postal_code:v('postalCode'),country:v('country'),aliases:v('aliases').split(',').map(x=>x.trim()).filter(Boolean)};if(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(identifier))p.email=identifier;else if(/^[+\d][\d\s().-]{6,}$/.test(identifier))p.phone=identifier;else p.aliases.unshift(identifier);return p}
async function api(path,o={}){const r=await fetch(API+path,o);if(!r.ok)throw Error(await r.text()||`HTTP ${r.status}`);return r.json()}
function setEngine(ok,text){$('engineBar').classList.toggle('online',ok);$('engineText').textContent=text}
async function checkEngine(){try{const h=await api('/health');setEngine(true,'Public removal API connected');$('brokerCount').textContent=`${h.registry.toLocaleString('en-IN')} sources`;return true}catch{setEngine(false,'Public removal API unavailable');$('brokerCount').textContent='Unavailable';return false}}
function card(item){const e=document.createElement('article');e.className='result status-submitted';const b=document.createElement('span');b.className='badge';b.textContent=item.status||'FOUND';const h=document.createElement('h3');h.textContent=item.broker?.company||item.company||'Unknown source';const p=document.createElement('p');p.textContent=item.broker?.domain||item.domain||'';if(item.broker?.optOutUrl){const a=document.createElement('a');a.className='result-link';a.href=item.broker.optOutUrl;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Official removal route →';e.append(b,h,p,a)}else e.append(b,h,p);return e}
async function scanAll(identifier){found=[];let offset=0,total=0;while(offset!==null){const r=await api('/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identifier,offset,limit:12})});total=r.registry_count;found.push(...r.sources.filter(x=>x.found));offset=r.next_offset;const checked=Math.min(offset??total,total);$('totalStat').textContent=total.toLocaleString('en-IN');$('submittedStat').textContent=found.length.toLocaleString('en-IN');$('manualStat').textContent=checked.toLocaleString('en-IN');$('runState').textContent=`Scanning · ${Math.round(checked/total*100)}%`;$('runTitle').textContent='Finding your data…';$('progressBar').style.width=`${Math.round(checked/total*100)}%`;renderFound();if(r.breaches?.breaches?.length){r.breaches.breaches.forEach(x=>found.push({broker:{company:x,domain:'Known breach exposure'},found:true,status:'BREACH'}));renderFound()} }return total}
function renderFound(){const g=$('resultGrid');g.replaceChildren();found.forEach(x=>g.appendChild(card(x)));$('submittedStat').textContent=found.length.toLocaleString('en-IN');$('runState').textContent=found.length?`${found.length} found`:'No matches found';}
async function startScan(){const p=profile();if(!p.identifier){$('identifier').focus();return}if(scanning)return;scanning=true;$('results').hidden=false;$('removeBtn').disabled=true;$('removeBtn').textContent='Scanning sources…';try{await scanAll(p.identifier);$('runTitle').textContent=found.length?'Your data was found':'No matching records found';$('progressBar').style.width='100%';$('removeBtn').disabled=false;$('removeBtn').textContent=found.length?'Remove all found data':'Scan again';if(found.length){$('removeBtn').onclick=()=>removeFound(p.identifier)}}catch(e){$('runState').textContent='Scan failed';alert(e.message)}finally{scanning=false;if(!found.length)$('removeBtn').disabled=false}}
async function removeFound(identifier){if(!found.length)return;$('removeBtn').disabled=true;$('removeBtn').textContent='Preparing removals…';try{const r=await api('/remove',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identifier,items:found})});$('runTitle').textContent='Removal actions ready';$('runState').textContent=`${r.count} sources`;const g=$('resultGrid');g.replaceChildren();r.tasks.forEach(t=>{const e=card({broker:t,status:'READY'});g.appendChild(e)});$('removeBtn').textContent='Removal routes ready';$('removeBtn').disabled=true}catch(e){alert(e.message);$('removeBtn').disabled=false}}
$('removeBtn').addEventListener('click',startScan);$('resetBtn').addEventListener('click',()=>{document.querySelectorAll('input').forEach(i=>i.value='');$('country').value='India';found=[];$('results').hidden=true;$('removeBtn').disabled=false;$('removeBtn').textContent='Find my data';$('removeBtn').onclick=startScan;$('identifier').focus()});checkEngine();